// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCnCsgzudSM-ZjE9xeGpx9YyRbH1u6ERM',
    appId: '1:644984516022:web:18a28630a112625d556517',
    messagingSenderId: '644984516022',
    projectId: 'carepatient-82822',
    authDomain: 'carepatient-82822.firebaseapp.com',
    storageBucket: 'carepatient-82822.appspot.com',
    measurementId: 'G-P3S3WPZNCC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7qxoGUNhyZJmXSeWmVWioc9gA486C84s',
    appId: '1:644984516022:android:d48132bd85e3ba52556517',
    messagingSenderId: '644984516022',
    projectId: 'carepatient-82822',
    storageBucket: 'carepatient-82822.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYw0lrX0jnMMNTctUYiFd3tMnjd2Le4FM',
    appId: '1:644984516022:ios:e90be1e160471415556517',
    messagingSenderId: '644984516022',
    projectId: 'carepatient-82822',
    storageBucket: 'carepatient-82822.appspot.com',
    androidClientId: '644984516022-aoiu4i0vreng98ahs85e513rjocj33ee.apps.googleusercontent.com',
    iosClientId: '644984516022-umqi0g1vulv7uhhmu2ae1rqeh67ma3bm.apps.googleusercontent.com',
    iosBundleId: 'com.example.carePatient',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYw0lrX0jnMMNTctUYiFd3tMnjd2Le4FM',
    appId: '1:644984516022:ios:10e990340ecf8479556517',
    messagingSenderId: '644984516022',
    projectId: 'carepatient-82822',
    storageBucket: 'carepatient-82822.appspot.com',
    androidClientId: '644984516022-aoiu4i0vreng98ahs85e513rjocj33ee.apps.googleusercontent.com',
    iosClientId: '644984516022-6j5qvatq1g2agn7si3krsvrp5sh7g27i.apps.googleusercontent.com',
    iosBundleId: 'com.example.carePatient.RunnerTests',
  );
}
